 version: '3.4'

services:
  webtiburontesttask:
    image: ${DOCKER_REGISTRY-}webtiburontesttask
    build:
      context: .
      dockerfile: WebTiburonTestTask/Dockerfile
  
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=c#4UZUg@JY
      - POSTGRES_USER=postgres
      - POSTGRES_DB=SurveyDB
    volumes:
      - pg_project:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
  